[".config/awesome/bling"]
type = "git-repo"
url = "https://github.com/BlingCorp/bling.git"
refreshPeriod = "168h"

[".config/awesome/sprimed"]
type = "git-repo"
url = "https://github.com/nils-degroot/sprimed.git"
refreshPeriod = "168h"

[".config/awesome/awesomewm-micky.git"]
type = "git-repo"
url = "https://github.com/basaran/awesomewm-micky.git"
refreshPeriod = "168h"
