[".config/awesome/bling"]
type = "file"
url = "https://github.com/BlingCorp/bling"
refreshPeriod = "168h"

[".config/awesome/rubato"]
type = "file"
url = "https://github.com/andOrlando/rubato"
refreshPeriod = "168h"
