[".config/awesome/bling"]
type = "git-repo"
url = "https://github.com/BlingCorp/bling"
refreshPeriod = "168h"

[".config/awesome/rubato"]
type = "git-repo"
url = "https://github.com/andOrlando/rubato"
refreshPeriod = "168h"
