use_nerdfont = true
notify = true

[theme]
background = "#1C1B19"
primary = "#FCE8C3"
secondary = "#918175"
title = "#519F50"
playing = "#519F50"
playing_selected = "#519F50"
playing_bg = "#121212"
highlight = "#519F50"
highlight_bg = "#121212"
error = "#FCE8C3"
error_bg = "#EF2F27"
statusbar = "#E02C6D"
statusbar_progress = "#2C78BF"
statusbar_bg = "#1C1B19"
cmdline = "#FCE8C3"
cmdline_bg = "#121212"
