return {
	{ "mrcjkb/rustaceanvim", version = "^4", ft = "rust" },
	{ "rust-lang/rust.vim", ft = "rust" },
	{ "tbastos/vim-lua", ft = "lua" },
	{ "aklt/plantuml-syntax", ft = "plantuml" },
	{ "evanleck/vim-svelte", ft = "svelte" },
	{ "prisma/vim-prisma", ft = "prisma" },
	"othree/html5.vim",
	"pangloss/vim-javascript",
	"leafgarland/typescript-vim",
	"jparise/vim-graphql",
	"apple/pkl-neovim",
	"grafana/vim-alloy",
	"elkowar/yuck.vim",
	"digitaltoad/vim-pug",
	"cakebaker/scss-syntax.vim",
}
