require("global.vim")
require("global.limelight")
require("global.easymotions")
require("global.citatie")
require("global.dashboard")
require("global.telescope")
require("global.rust-vim")
require("global.zettelkasten")
