import = ["/home/nils/.config/alacritty/srcery.toml"]

[font]
size = 12.0

[font.bold]
family = "Iosevka"
style = "Bold"

[font.bold_italic]
family = "Iosevka"
style = "Bold Italic"

[font.italic]
family = "Iosevka"
style = "Italic"

[font.normal]
family = "Iosevka"
style = "Regular"

[shell]
program = "nu"

[window.dimensions]
columns = 85
lines = 16

#[window.dimensions.padding]
#dynamic_padding = true
#x = 0
#y = 0
